version: '3'
services:
  app:
    restart: always
    build:
      context: Python/
      dockerfile: Dockerfile
    volumes:
      - ./Python/src/:/app/src
      - ./data/:/app/data
    working_dir:
      /app
    image: jupyter-notebook_pytorch
    container_name: JN_PyTorch
    ports:
      - 8888:8888
    tty: true
    command: jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''